import { TargetType } from '../../shared/enums/target-type.enum';
import { Target } from '../../shared/interfaces/target.interface';
import { TargetAbilities } from '../models/target-abilities.model';

export class BuildingsState {
  public static buildings: Target[] = [
    {
      id: 1,
      name: 'West Tower',
      image: 'assets/Castle/Tower_2.png',
      type: TargetType.PLAYERBASE,
      combatAttributes: {
        currentHealth: 500,
        health: 500,
        minAttack: 0,
        maxAttack: 0,
        blockChance: 0,
        critChance: 0,
        minMoneyDrop: 0,
        maxMoneyDrop: 0,
        minMiningAttack: 0,
        maxMiningAttack: 0,
        miningCritChance: 0,
      },
      physicalAttributes: {
        width: 230,
        height: 190,
        speed: 0,
        initialPosition: 2410,
        range: 500,
        position: 1,
        initialOrientation: 1,
        backgroundX: 0,
        projectileStartX: 2457,
        projectileStartY: 145,
      },
      aboveNotifications: [],
      effects: [],
      abilities: [TargetAbilities.getAbility('ProjectileArrow')],
      boundCssClass: [],
      currentTarget: null,
    },
    {
      id: 2,
      name: 'House',
      image: 'assets/Castle/castle_0.png',
      type: TargetType.PLAYERBASE,
      combatAttributes: {
        currentHealth: 500,
        health: 500,
        minAttack: 0,
        maxAttack: 0,
        blockChance: 0,
        critChance: 0,
        minMoneyDrop: 0,
        maxMoneyDrop: 0,
        minMiningAttack: 0,
        maxMiningAttack: 0,
        miningCritChance: 0,
      },
      physicalAttributes: {
        width: 240,
        left: 2700,
        bottom: 25,
        initialPosition: 2700,
        range: 200,
        pause: 0,
        position: 1,
        initialOrientation: 1,
        backgroundX: 0,
      },
      aboveNotifications: [],
      effects: [],
      boundCssClass: [],
      currentTarget: null,
    },
    {
      id: 3,
      name: 'Est Tower',
      image: 'assets/Castle/Tower_2.png',
      type: TargetType.PLAYERBASE,
      combatAttributes: {
        currentHealth: 500,
        health: 500,
        minAttack: 0,
        maxAttack: 0,
        blockChance: 0,
        critChance: 0,
        minMoneyDrop: 0,
        maxMoneyDrop: 0,
        minMiningAttack: 0,
        maxMiningAttack: 0,
        miningCritChance: 0,
      },
      physicalAttributes: {
        width: 230,
        height: 190,
        initialPosition: 3258,
        range: 500,
        position: -1,
        initialOrientation: -1,
        backgroundX: 0,
        projectileStartX: 3365,
        projectileStartY: 145,
      },
      aboveNotifications: [],
      effects: [],
      boundCssClass: [],
      abilities: [TargetAbilities.abilities.ProjectileArrow],
      currentTarget: null,
    },
  ];
}
